### PR TITLE
add pass FaceAware Finished image modify

### PR DESCRIPTION
**Pull request by CocoaML**
SomeTimes , The project should know the image FaceAware Finished,  so I modify the code.

add pass FaceAware Finished image modify.

This is a Notification to pass FaceAwared image value modify, 
And I think Use block should be delightful.  What do you think ?

### CODE REVIEW

**Comment by iKisliy** [comment]
At my opinion, there's should be closure for callback, not NotificationCenter. It's a workaround, not really solution

**Comment by CocoaML** [comment]
Yeah,  I agree with you.

**Comment by CocoaML** [comment]
> At my opinion, there's should be closure for callback, not NotificationCenter. It's a workaround, not really solution

When focus on faces for the image of cell specified in UITableView,  How can I set the FaceAware image on the ImageView ?

I code a method, but It does not work for me. And I do not know Why ?
Here, This is my code.

`    func setLocalFaceImageAndFrame(aImage: UIImage?, aFrame: CGRect?) {
        let layer = self.imageLayer()
        layer.contents = aImage!.cgImage
        layer.frame = aFrame!
    }`

**Comment by CocoaML** [comment]
> At my opinion, there's should be closure for callback, not NotificationCenter. It's a workaround, not really solution

When focus on faces for the image of cell specified in UITableView, How can I set the FaceAware image on the ImageView ?

Here，This is my code .
`
func setLocalFaceImageAndFrame(aImage: UIImage?, aFrame: CGRect?) {
        let layer = self.imageLayer() 
        layer.contents = aImage!.cgImage 
        layer.frame = aFrame! 
}
`

**Comment by BeauNouvelle** [comment]
I agree that we should be using a closure or even a delegate for callback. 

As for your issues with the tableview, I should have some time this weekend to check it out. I also think this library could do with some kind of caching to help speed things up. A little tricky with it being an extension.

**Comment by BeauNouvelle** [comment]
Just an update. I've now got closure's working, and will push to a new branch for you all to have a look at sometime this week.

**Comment by CocoaML** [comment]
> Just an update. I've now got closure's working, and will push to a new branch for you all to have a look at sometime this week.

Thanks, I am really looking forward to your code.

**Comment by BeauNouvelle** [comment]
You can find it over here:
https://github.com/BeauNouvelle/FaceAware/pull/28

**Comment by BeauNouvelle** [comment]
I've merged in the other branch that solves the same issue as this one. Closing.

**Pull request closed without merging**
